### ISSUE TITLE
Update documentation how to continue on failure

### ISSUE THREAD

**Issue by kzantow** [anchore/scan-action#128]
This PR was opened for the use case of continuing on failure to check an exit code later. But there is already a way to do this with GitHub Actions, we should document this:

```yaml
- uses: anchore/scan-action@v3
  id: scan
  continue-on-error: true
  ...
- run: exit 1
  if: ${{steps.scan.outcome == 'failure'}}
```

Example: https://github.com/kzantow-anchore/sbom-action-test/blob/scan-test/.github/workflows/scan-test.yml
