### ISSUE TITLE
Dismissed findings fail in subsequent checks

### ISSUE THREAD

**Issue by bryopsida** [anchore/scan-action#142]
I've dismissed a few alerts in the security/code scanning alerts page.

But whenever the scan action is executed it detects these vulnerabilities as being new and fails the check under `Code scanning results` 

The top level job has the following permissions:

``` yaml
permissions:
  security-events: write
```

And I'm running the scan action like this:

``` yaml
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ steps.meta.outputs.tags }}
          fail-build: false
          severity-cutoff: "critical"
          acs-report-enable: true
```

Any ideas on why it's reporting the dismissed (and already existing) alerts as new in the check?
