### ISSUE TITLE
Action refuses to accept output-format parameter

### ISSUE THREAD

**Issue by maartenh** [anchore/scan-action#186]
The recently added and documented `output-format` parameter is not accepted by the action.
A scanning step such as
```yaml
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}/catalog-service"
          fail-build: true
          output-format: json
          acs-report-enable: false
```
will fail with an error
`Unexpected input(s) 'output-format', valid inputs are ['image', 'path', 'sbom', 'fail-build', 'acs-report-enable', 'severity-cutoff']`

This is because when the feature was implemented the file `./action.yml` wasn't updated with the new parameter.

I have a fix locally, will attempt to make a PR for this.
