### ISSUE TITLE
JSON output not being display

### ISSUE THREAD

**Issue by DiegoLara03** [anchore/scan-action#207]
Hi
I have this configuration, but when I configured the output to JSON , looks like it´s not working.

```
    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: xxxxx:xxxxxx
        severity-cutoff: "high"
        fail-build: false
        output-format: json
    - name: Create comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ${{ steps.scan.outputs.json }}
```
Getting this:
```
grype output...
  Executing: grype -o json --fail-on high dat-docker.jfrog.io/baires-account-web:280da54
  1 error occurred:
  	* discovered vulnerabilities at or above the severity threshold
Warning: Failed minimum severity level. Found vulnerabilities with level 'high' or higher
Run thollander/actions-comment-pull-request@v2
  with:
    GITHUB_TOKEN: ***
    mode: upsert
    create_if_not_exists: true
Error: Either "filePath" or "message" should be provided as input
```
Interesting part is that when I changed to serif it´s behaving different.

```
    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: xxxxx:xxxxxx
        severity-cutoff: "high"
        fail-build: false
        output-format: sarif
    - name: Create comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ${{ steps.scan.outputs.sarif }}
```        
Getting this, of course getting an error of the other action, but that´s a different problems.

```
grype output...
  Executing: grype -o sarif --fail-on high dat-docker.jfrog.io/baires-account-web:280da54
  1 error occurred:
  	* discovered vulnerabilities at or above the severity threshold
  
  
Warning: Failed minimum severity level. Found vulnerabilities with level 'high' or higher
Run thollander/actions-comment-pull-request@v2
  with:
    filePath: ./results.sarif
    GITHUB_TOKEN: ***
    mode: upsert
    create_if_not_exists: true
Error: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
```
Not sure if there's a problem with the output for JSON.
