### ISSUE TITLE
Getting unauthorised for github container registry

### ISSUE THREAD

**Issue by Sabreen-Parveen** [anchore/scan-action#232]
I am using this action to scan images present in github container registry, I have set the registery-username variable to my username and have used ${{ secrets.GITHUB_TOKEN }} for my password. But when the action is running it is giving me unauthorised. To authenticate with GITHUB_TOKEN, I have followed this [github doc](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token).

My github action:
```
scan:
    name: 🛡️ Scan docker images
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    needs: get_images
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get_images.outputs.images) }}
    steps:
      - name: scan ghcr images
        uses: anchore/scan-action@v3
        if: ${{ startsWith( matrix.images, 'ghcr.io' ) }}
        id: scan-ghcr
        with:
         image: ${{ matrix.images }}
         fail-build: true
         severity-cutoff: critical
         output-format: json
         registry-username: sabreen-parveen
         registry-password: ${{ secrets.GITHUB_TOKEN }}
```

## Error
Getting following warning and error message:
<img width="1015" alt="image" src="https://github.com/anchore/scan-action/assets/53360510/a30d2778-8e39-4fc3-ae25-5be35a7f1e65">

<img width="1018" alt="image" src="https://github.com/anchore/scan-action/assets/53360510/7a4792e3-568c-4484-9699-d05fce912af7">

**Comment by lek-x** [comment]
The same behavior.
```
Scan-image:
    needs: [Build-docker-Airflow]
    runs-on:
      - self-hosted
    steps:
      - name: Scan image
        uses: anchore/scan-action@v3.3.6
        with:
          image: ${{ env.repo }}/${{ secrets.DOCKER_USERNAME }}/${{ env.image_name }}:$GITHUB_RUN_NUMBER
          fail-build: false
          registry-username: ${{ secrets.DOCKER_USERNAME }}
          registry-password: ${{ secrets.DOCKER_PASSWORD }} 
```




![image](https://github.com/anchore/scan-action/assets/34778894/ad7af629-2b36-44a6-88c5-d2c16decc3df)
