### ISSUE TITLE
Unable to store output in "table" format

### ISSUE THREAD

**Issue by Jiri-Stary** [anchore/scan-action#238]
Currently there is no way to store output in table format.

I am running few different scanners in my workflow an would like to control when i show the output to the user.
Currently there is no way how to store the output to a text file in table format.

**Comment by kzantow** [comment]
Hi @Jiri-Stary -- you're right, today if you use the `table` output format, this defaults to output to the log instead of a file, however there is a workaround if you really want this output to a file, you can use the `GRYPE_FILE` environment variable, e.g.:
```yaml
      - uses: anchore/scan-action@main
        id: scan-table-to-file
        with:
          image: alpine:3.15
          fail-build: false
          severity-cutoff: medium
          output-format: table
        env:
          GRYPE_FILE: table.out
```
Example run here: https://github.com/kzantow-anchore/scan-action-test/actions/runs/10924951451/job/30325259711#step:5:9
