### ISSUE TITLE
v2 has lots of false positives

### ISSUE THREAD

**Issue by dvalentiate** [anchore/scan-action#55]
anchore/scan-action@v2 identifies 24 critical, 81 High, 76 medium, 31 low vulnerabilities on an empty `node:12-alpine` project with a `package.json` with no dependencies.

My team was using `anchore/scan-action@master` (now `anchore/scan-action@main`) but we are switching to only using `anchore/scan-action@v1` until this settles down.

Files to reproduce:
`Dockerfile`
```
FROM node:12-alpine

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm ci --production
```

`package.json`
```
{
  "name": "anchor-test",
  "license": "ISC"
}
```

`package-lock.json`
```
{
  "name": "anchor-test",
  "lockfileVersion": 1
}
```

`.github/workflows/anchor.yml`
```
on:
  push

name: Docker image vulnerability scan

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Docker image
      id: build-image
      env:
        IMAGE_NAME: ${{ github.repository }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        echo "::set-env name=image::$IMAGE_NAME:$IMAGE_TAG"

    - name: Scan Docker image
      uses: anchore/scan-action@v2
      id: anchore-scan
      with:
        image: "${{ github.repository }}:${{ github.sha }}"
        severity-cutoff: critical
        fail-build: true
```

**Comment by dvalentiate** [comment]
An example of one of the false positives:

> atob 2.0.3 and earlier allocates uninitialized Buffers when number is passed in input on Node.js 4.x and below

> /usr/local/lib/node_modules/npm/node_modules/psl/yarn.lock

This is on a node:12-alpine build. So this issue isn't relevant, `atob` is not installed and this finds a problem in `yarn.lock` but yarn isn't installed on this system.

```
  {
   "vulnerability": {
    "id": "CVE-2018-3745",
    "severity": "Critical",
    "links": [
     "https://hackerone.com/reports/321686"
    ],
    "description": "atob 2.0.3 and earlier allocates uninitialized Buffers when number is passed in input on Node.js 4.x and below.",
    "cvssV2": {
     "baseScore": 6.4,
     "exploitabilityScore": 10,
     "impactScore": 4.9,
     "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:P"
    },
    "cvssV3": {
     "baseScore": 9.1,
     "exploitabilityScore": 3.9,
     "impactScore": 5.2,
     "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
    }
   },
   "matchDetails": {
    "matcher": "javascript-matcher",
    "searchKey": {
     "cpe": "cpe:2.3:*:*:atob:0.6.0:*:*:*:*:*:*:*"
    },
    "matchedOn": {
     "constraint": "<= 2.0.3 (unknown)",
     "cpes": [
      "cpe:2.3:a:atob_project:atob:*:*:*:*:*:node.js:*:*"
     ]
    }
   },
   "artifact": {
    "name": "atob",
    "version": "0.6.0",
    "type": "yarn",
    "foundBy": [
     "javascript-cataloger"
    ],
    "locations": [
     {
      "path": "/usr/local/lib/node_modules/npm/node_modules/psl/yarn.lock",
      "layerIndex": 1
     }
    ]
   }
  },
```

**Comment by zhill** [comment]
@dvalentiate thanks for filing this. We're taking a look at this.

**Comment by zhill** [comment]
@dvalentiate we're working on this in the underlying [Grype](https://github.com/anchore/grype) tool via Syft library (the detector code) in anchore/syft#199 as indicated above.

**Comment by alfredodeza** [comment]
@dvalentiate could you double check if the recent bump to a newer `grype` version (0.5.0 now) helps with this problem? We haven't cut a new release yet, so your action would need to point to `anchore/scan-action@main`

**Comment by dvalentiate** [comment]
using `anchor/scan-action@main` works and appears to report reasonable results.

I've updated the `.github/workflows/anchor.yml` in the example above to account for `main` instead of `v2` and to replace the now deprecated and unrelated `::set-env`.

```
on:
  push

name: Docker image vulnerability scan

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Docker image
      id: build-image
      env:
        IMAGE_NAME: ${{ github.repository }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Scan Docker image
      uses: anchore/scan-action@main
      id: anchore-scan
      with:
        image: "${{ github.repository }}:${{ github.sha }}"
        severity-cutoff: critical
        fail-build: true
```
