### ISSUE TITLE
Error: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by rupeshphuyal** [anchore/scan-action#70]
Hi,

I have the following steps defined in github actions but it is giving the following error after scanning the image.  

`Error: TypeError: Cannot read property '0' of undefined
`
```
 # Scan Docker image 
    - name: Scan image
      uses: actions/scan-action@v2
      id: scan
      with:
        image: ${{ steps.build-image.outputs.image }}
        acs-report-enable: true
        severity-cutoff: critical 
          
    - name: upload Anchore scan SARIF report
      uses: actions/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
```
